[build]
  base = ""
  command = "cd client && npm install && npm run build"
  publish = "client/build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[dev]
  framework = "#custom"
  command = "cd client && npm start"
  port = 9999
  targetPort = 3000
  publish = "client/build"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
