[build]
  base = ""
  command = "cd client && npm install && npm run build"
  publish = "client/build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "cd client && npm start"
  port = 3000
  targetPort = 3000
  publish = "client/build"
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  external_node_modules = ["@neondatabase/serverless"]
  node_bundler = "esbuild"
